Fix benchmark mock implementation to work correctly
The benchmark was causing a TypeError: q is not a function in CI. Additionally it was failing typescript checks. This updates the test mock to properly mirror prisma's mock logic safely.

Co-authored-by: michaelcrosato <58404198+michaelcrosato@users.noreply.github.com>